CORALSCAPES_LABELS = {
     0: "Background",
     1: "Coral (Acropora)",
     2: "Coral (Montipora)",
     3: "Coral (Pocillopora)",
     4: "Coral (Porites massive)",
     5: "Coral (Porites branching)",
     6: "Dead Coral",
     7: "Bleached Coral",
     8: "Crustose Coralline Algae",
     9: "Macroalgae",
    10: "Turf Algae",
    11: "Soft Coral",
    12: "Sponges",
    13: "Rubble",
    14: "Sand",
    15: "Rock",
    16: "Seagrass",
    17: "Water Column",
    18: "Shadow",
    19: "Silt",
    20: "Coral (Other)",
    21: "Unknown Coral",
    22: "Bleached Montipora",
    23: "Bleached Acropora",
    24: "Bleached Pocillopora",
    25: "Bleached Porites",
    26: "Bleached Soft Coral",
    27: "Bleached Other",
    28: "Bleached Dead Coral",
    29: "Bleached Rubble",
    30: "Bleached Sponges",
    31: "Bleached Rock",
    32: "Bleached Sand",
    33: "Bleached Seagrass",
    34: "Bleached Water",
    35: "Bleached Shadow",
    36: "Bleached Silt",
    37: "Bleached Algae",
    38: "Bleached Crustose Coralline",
    39: "Bleached Macroalgae"
}